# Generated by Django 4.2.6 on 2023-11-21 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
    ]
